version: '3.4'

services:
  demo.apidesign.cache:
    image: ${DOCKER_REGISTRY-}demoapidesigncache
    build:
      context: .
      dockerfile: Demo.ApiDesign.Cache/Dockerfile
    depends_on:
          - db
  db:
      image: "mcr.microsoft.com/mssql/server"
      environment:
          SA_PASSWORD: "MySecret_9000"
          ACCEPT_EULA: "Y"
      ports:
        - "111:1433"